module.exports = [
  {
    ETHNO: "1",
    symptom: "Abcess",
    remedy: "Achillea",
    SPECIES: "millefolium",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Achillea millefolium",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "1",
    symptom: "Knee pain",
    remedy: "Achillea",
    SPECIES: "millefolium",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Achillea millefolium",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "2",
    symptom: "Abcess",
    remedy: "Castilla",
    SPECIES: "elastica",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Moraceae",
    CNAME: "",
    COUNTRY: "Mexico",
    REFERENCE: "Standley",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Castilla elastica",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "3",
    symptom: "Abcess",
    remedy: "Pistia",
    SPECIES: "stratiotes",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Araceae",
    CNAME: "",
    COUNTRY: "Elsewhere",
    REFERENCE: "Duke,1972",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Pistia stratiotes",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "4",
    symptom: "Abdomen",
    remedy: "Achillea",
    SPECIES: "sibirica",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Achillea sibirica",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "5",
    symptom: "Abdomen",
    remedy: "Adenia",
    SPECIES: "lobata",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Passifloraceae",
    CNAME: "",
    COUNTRY: "Upper Volta",
    REFERENCE: "Ayensu",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Adenia lobata",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "6",
    symptom: "Abdomen",
    remedy: "Aegle",
    SPECIES: "marmelos",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Rutaceae",
    CNAME: "",
    COUNTRY: "India(Santal)",
    REFERENCE: "Eb24: 243",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Aegle marmelos",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "7",
    symptom: "Abdomen",
    remedy: "Afzelia",
    SPECIES: "africana",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Fabaceae",
    CNAME: "",
    COUNTRY: "Upper Volta",
    REFERENCE: "Ayensu",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Afzelia africana",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "8",
    symptom: "Abdomen",
    remedy: "Ageratum",
    SPECIES: "conyzoides",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "Africa",
    REFERENCE: "Ayensu",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Ageratum conyzoides",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "9",
    symptom: "Abdomen",
    remedy: "Agrimonia",
    SPECIES: "pilosa",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Rosaceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Agrimonia pilosa",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "10",
    symptom: "Abdomen",
    remedy: "Ailanthus",
    SPECIES: "fauveliana",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Simaroubaceae",
    CNAME: "",
    COUNTRY: "",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Ailanthus fauveliana",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "11",
    symptom: "Abdomen",
    remedy: "Alchornea",
    SPECIES: "cordifolia",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Euphorbiaceae",
    CNAME: "",
    COUNTRY: "Upper Volta",
    REFERENCE: "Ayensu",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Alchornea cordifolia",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "12",
    symptom: "Abdomen",
    remedy: "Allophylus",
    SPECIES: "sp",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Sapindaceae",
    CNAME: "",
    COUNTRY: "Philippines",
    REFERENCE: "Altschul",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Allophylus sp",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "13",
    symptom: "Abdomen",
    remedy: "Alternanthera",
    SPECIES: "repens",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Amaranthaceae",
    CNAME: "",
    COUNTRY: "Ghana",
    REFERENCE: "Ayensu",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Alternanthera repens",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "14",
    symptom: "Abdomen",
    remedy: "Amaranthus",
    SPECIES: "viridis",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Amaranthaceae",
    CNAME: "",
    COUNTRY: "Venezuela",
    REFERENCE: "Pittier",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Amaranthus viridis",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "15",
    symptom: "Abdomen",
    remedy: "Amomum",
    SPECIES: "costatum",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Zingiberaceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Amomum costatum",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "16",
    symptom: "Abdomen",
    remedy: "Anemone",
    SPECIES: "cernua",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Ranunculaceae",
    CNAME: "Pai T'Ou Weng",
    COUNTRY: "China",
    REFERENCE: "Bliss",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Anemone cernua",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "17",
    symptom: "Abdomen",
    remedy: "Anotis",
    SPECIES: "hirsuta",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "",
    CNAME: "",
    COUNTRY: "Java",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Anotis hirsuta",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "18",
    symptom: "Abdomen",
    remedy: "Aquilaria",
    SPECIES: "agallocha",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Thymelaeaceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Aquilaria agallocha",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "19",
    symptom: "Abdomen",
    remedy: "Aristolochia",
    SPECIES: "bracteata",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Aristolochiaceae",
    CNAME: "",
    COUNTRY: "Sudan",
    REFERENCE: "Broun",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Aristolochia bracteata",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "20",
    symptom: "Abdomen",
    remedy: "Aristolochia",
    SPECIES: "debilis",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Aristolochiaceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Aristolochia debilis",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "21",
    symptom: "Abdomen",
    remedy: "Artemisia",
    SPECIES: "apiacea",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Artemisia apiacea",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "22",
    symptom: "Abdomen",
    remedy: "Asarum",
    SPECIES: "canadense",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Aristolochiaceae",
    CNAME: "",
    COUNTRY: "US(Cherokee)",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Asarum canadense",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "23",
    symptom: "Abdomen",
    remedy: "Aspidistra",
    SPECIES: "elatior",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Liliaceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Aspidistra elatior",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "24",
    symptom: "Abdomen",
    remedy: "Atractylis",
    SPECIES: "ovata",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Atractylis ovata",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "25",
    symptom: "Abdomen",
    remedy: "Boerhaavia",
    SPECIES: "diffusa",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Nyctaginaceae",
    CNAME: "",
    COUNTRY: "India(Santal)",
    REFERENCE: "Eb24: 246",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Boerhaavia diffusa",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "26",
    symptom: "Abdomen",
    remedy: "Lindernia",
    SPECIES: "veronicaefolia",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Scrophulariaceae",
    CNAME: "",
    COUNTRY: "India(Santal)",
    REFERENCE: "Eb24: 246",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Lindernia veronicaefolia",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "27",
    symptom: "Abdomen",
    remedy: "Bupleurum",
    SPECIES: "falcatum",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Apiaceae",
    CNAME: "Ch'Ai Hu",
    COUNTRY: "China",
    REFERENCE: "Bliss",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Bupleurum falcatum",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "28",
    symptom: "Abdomen",
    remedy: "Bupleurum",
    SPECIES: "octoradiatum",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Apiaceae",
    CNAME: "Tz'U Hu",
    COUNTRY: "China",
    REFERENCE: "Bliss",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Bupleurum octoradiatum",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "29",
    symptom: "Abdomen",
    remedy: "Cajanus",
    SPECIES: "cajan",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Fabaceae",
    CNAME: "",
    COUNTRY: "Malaya",
    REFERENCE: "Eb22: 98",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Cajanus cajan",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "30",
    symptom: "Abdomen",
    remedy: "Calamus",
    SPECIES: "draco",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Arecaceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Calamus draco",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "31",
    symptom: "Abdomen",
    remedy: "Callicarpa",
    SPECIES: "cana",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Lamiaceae",
    CNAME: "",
    COUNTRY: "Elsewhere",
    REFERENCE: "Woi.2",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Callicarpa cana",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "32",
    symptom: "Abdomen",
    remedy: "Canthium",
    SPECIES: "monstrosum",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Rubiaceae",
    CNAME: "",
    COUNTRY: "Philippines",
    REFERENCE: "Altschul",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Canthium monstrosum",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "33",
    symptom: "Abdomen",
    remedy: "Carpesium",
    SPECIES: "divaricatum",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Carpesium divaricatum",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "34",
    symptom: "Abdomen",
    remedy: "Celosia",
    SPECIES: "cristata",
    SPAUT: "L.",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Amaranthaceae",
    CNAME: "Boenga tali",
    COUNTRY: "Java",
    REFERENCE: "Burkill,1966",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Celosia cristata",
    TAXAUTHOR: "L.",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "35",
    symptom: "Abdomen",
    remedy: "Cinnamomum",
    SPECIES: "cambodianum",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Lauraceae",
    CNAME: "",
    COUNTRY: "Elsewhere",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Cinnamomum cambodianum",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "36",
    symptom: "Abdomen",
    remedy: "Cinnamomum",
    SPECIES: "camphora",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Lauraceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Cinnamomum camphora",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "37",
    symptom: "Abdomen",
    remedy: "Cissus",
    SPECIES: "rubiginosa",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Vitaceae",
    CNAME: "",
    COUNTRY: "Elsewhere",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Cissus rubiginosa",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "38",
    symptom: "Abdomen",
    remedy: "Citrus",
    SPECIES: "aurantium",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Rutaceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Nas",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Citrus aurantium",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "39",
    symptom: "Abdomen",
    remedy: "Citrus",
    SPECIES: "sinensis",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Rutaceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Citrus sinensis",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "40",
    symptom: "Abdomen",
    remedy: "Cleome",
    SPECIES: "brachycarpa",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Capparaceae",
    CNAME: "",
    COUNTRY: "Elsewhere",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Cleome brachycarpa",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "41",
    symptom: "Abdomen",
    remedy: "Corydalis",
    SPECIES: "ternata",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Papaveraceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Corydalis ternata",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "42",
    symptom: "Abdomen",
    remedy: "Cryptocoryne",
    SPECIES: "spiralis",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Araceae",
    CNAME: "",
    COUNTRY: "Sri Lanka",
    REFERENCE: "Woi.2",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Cryptocoryne spiralis",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "43",
    symptom: "Abdomen",
    remedy: "Curcuma",
    SPECIES: "domestica?",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Zingiberaceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Curcuma domestica?",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "44",
    symptom: "Abdomen",
    remedy: "Cyperus",
    SPECIES: "rotundus",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Cyperaceae",
    CNAME: "",
    COUNTRY: "China",
    REFERENCE: "Hunan",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Cyperus rotundus",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "45",
    symptom: "Abdomen",
    remedy: "Desmodium",
    SPECIES: "heterophyllum",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Fabaceae",
    CNAME: "",
    COUNTRY: "Elsewhere",
    REFERENCE: "Woi.3",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Desmodium heterophyllum",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "46",
    symptom: "Abdomen",
    remedy: "Dialium",
    SPECIES: "guineense",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Fabaceae",
    CNAME: "",
    COUNTRY: "Africa",
    REFERENCE: "Ayensu",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Dialium guineense",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "47",
    symptom: "Abdomen",
    remedy: "Dichroa",
    SPECIES: "febrifuga",
    SPAUT: "LOUR.",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Hydrangeaceae",
    CNAME: "Tataroeman",
    COUNTRY: "Java",
    REFERENCE: "Burkill,1966",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Dichroa febrifuga",
    TAXAUTHOR: "LOUR.",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "48",
    symptom: "Abdomen",
    remedy: "Elatostema",
    SPECIES: "sessile",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Urticaceae",
    CNAME: "",
    COUNTRY: "Malaysia",
    REFERENCE: "Woi.3",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Elatostema sessile",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "49",
    symptom: "Abdomen",
    remedy: "Elastostemma",
    SPECIES: "sessile",
    SPAUT: "FORST.",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "",
    CNAME: "Sisek tenggiling (Anteater..)",
    COUNTRY: "Pahang",
    REFERENCE: "Burkill,1966",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Elastostemma sessile",
    TAXAUTHOR: "FORST.",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "50",
    symptom: "Abdomen",
    remedy: "Elephantopus",
    SPECIES: "scaber",
    SPAUT: "L.",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "Tutup bumi (Bung of the earth)",
    COUNTRY: "Johore",
    REFERENCE: "Burkill,1966",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Elephantopus scaber",
    TAXAUTHOR: "L.",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "51",
    symptom: "Abdomen",
    remedy: "Entada",
    SPECIES: "phaseoloides",
    SPAUT: "MERR.",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Fabaceae",
    CNAME: "Bendoh",
    COUNTRY: "Java",
    REFERENCE: "Burkill,1966",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Entada phaseoloides",
    TAXAUTHOR: "MERR.",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "52",
    symptom: "Abdomen",
    remedy: "Ethulia",
    SPECIES: "conyzoides",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "Africa(Zulu)",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Ethulia conyzoides",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "53",
    symptom: "Abdomen",
    remedy: "Ethulia",
    SPECIES: "conyzoides",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "Africa",
    REFERENCE: "Woi.3",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Ethulia conyzoides",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  }
]