module.exports = [
  {
    ETHNO: "1",
    symptoms: ["Abcess"],
    remedyName: "Achillea",
    ratings: [],
    ratingAverage: 0,
    totalNumberofRatings: 0,
    SPECIES: "millefolium",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Achillea millefolium",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "1",
    symptoms: ["Knee pain"],
    remedyName: "Achillea",
    ratings: [],
    ratingAverage: 0,
    totalNumberofRatings: 0,
    SPECIES: "millefolium",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Achillea millefolium",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  },
  {
    ETHNO: "1",
    symptoms: ["Head ache"],
    remedyName: "Paracetamol",
    ratings: [],
    ratingAverage: 0,
    totalNumberofRatings: 0,
    SPECIES: "millefolium",
    SPAUT: "",
    SPRANK: "",
    SPXNAM: "",
    SPXAUT: "",
    FAMILY: "Asteraceae",
    CNAME: "",
    COUNTRY: "",
    REFERENCE: "Uphof",
    LONGREF: "",
    EFFECTIVE: "",
    TAXON: "Achillea millefolium",
    TAXAUTHOR: "",
    USERID: "DUKE",
    CREATED: "02-FEB-98",
    MODIFIED: ""
  }
]